graycoreio/github-actions-magento2

.github/workflows/install.yaml
.github/workflows/unit.yaml
_test/demo-package/composer.json
_test/demo-package/phpunit.xml
unit-test/action.yml

```
[ ] Bugfix
[x] Feature
```
Currently, we have code littered about in:
1. https://github.com/graycoreio/magento2-cors
2. https://github.com/graycoreio/magento2-stdlogging
3. https://github.com/graycoreio/magento2-daffodil
4. https://github.com/graycoreio/magento2-guest-orders-graphql
That has become extremely tedious to maintain over time.
Fixes: N/A
I'm coalescing all of these testing patterns into the same repository.
```
[ ] Yes
[x] No
```

feat: add unit test action

---

.github/workflows/integration-README.md
README.md
installation-test/README.md
unit-test/README.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```

docs: document unit, integration, and installation

---

.github/workflows/install.yaml
README.md
supported-version/README.md
supported-version/action.yml
supported-version/supported.json

```
[ ] Bugfix
[x] Feature
```
There's no well-defined way (that I've found on the internet) to determine the matrix of underlying technology support for Magento. Most often, even the Magento dev docs are wildly inaccurate.
Fixes: N/A
This adds a stable file (and re-usable action) that can be used in Github Actions to verify behavior of a codebase.
```
[ ] Yes
[x] No
```

feat: add supported version matrix

---

.github/workflows/_internal-integration.yaml
.github/workflows/integration-README.md
.github/workflows/integration.yaml
supported-version/supported.json

```
[ ] Bugfix
[x] Feature
```
Currently, we don't test across the Magento version matrix.
Fixes: N/A
We do integration test across the Magento version matrix.
```
[ ] Yes
[x] No
```

feat: add matrix to integration tests

---

.github/workflows/_internal-integration.yaml
supported-version/action.yml

```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```

fix(supported-version): matrix innaccessible outside of repo

---

.github/workflows/_internal-integration.yaml

```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```

chore: allow internal integration workflow to be called manually

---

.github/workflows/integration.yaml
_test/demo-package/composer.json
_test/demo-package/composer.lock
installation-test/action.yml

```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```

feat: use Mage-OS by default

---

.github/workflows/integration-README.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
The default changed in #18 and the docs were not updated.
Fixes: N/A
I updated the docs.
```
[ ] Yes
[x] No
```

Update repo in integration workflow readme file

---

.github/PULL_REQUEST_TEMPLATE.md

Fix broken URL in GitHub Pull Request template

---

.github/workflows/integration.yaml

Only for composer 1.x installations, use parallel download plugin to speed up the installation process
Fixes: N/A

Install composer plugin for parallel downloads

---

supported-version/README.md

Checkout is not required for calculating supported versions

---

.github/workflows/_internal-get-magento-version.yaml
README.md
get-magento-version/README.md
get-magento-version/action.yml

Currently, we have no way to compute the Magento version in well-defined and discrete way.
Fixes: N/A
We now have a way to compute the Magento version.

feat(get-magento-version): add get-magento-version action

---

.github/workflows/integration.yaml

Currently,  we have a custom script that compute the Magento version. I moved this to a re-usable action in #72 .
Fixes: N/A
I now use the action created in #72

chore(deps): use get-magento-verison

---

.github/workflows/integration.yaml
coding-standard/action.yml
get-magento-version/action.yml
installation-test/action.yml
unit-test/action.yml

Fixes: https://github.com/graycoreio/github-actions-magento2/issues/70
N/A

Fix ::set-output deprecations

---

README.md
cache-magento/README.md
cache-magento/action.yml

Currently, the cache key for composer for Magento is non-standard, which leads to cache misses across various workflows and actions. 
Fixes: N/A
This standardizes it to a unified action to improve cache hits.
Note that I've added `mode` and `magento_directory` as inputs even though they're unused as I'd like to experiment with these in the future and adding them later would be breaking.

feat: add `cache-magento` action

---

.github/workflows/_internal-setup-magento.yaml
README.md
setup-magento/README.md
setup-magento/action.yml

feat(setup-magento): add a new action to setup Magento

---

.github/workflows/integration-README.md

docs(integration): fix auth instructions link

---

.github/workflows/_internal-coding-standard.yaml
.github/workflows/_internal-install.yaml
.github/workflows/_internal-integration.yaml

Currently, we test many different environments. This is becoming unsustainable as [older pieces of software experience brownouts. ](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/). I just simply do not have the time to maintain these older environments. 
Fixes: N/A
Now, we only guarantee that the actions work with the `currently-supported` versions of Magento.

ci: only test supported versions

---

setup-magento/action.yml

feat(setup-magento): add support for composer auth

---

.github/workflows/_internal-install.yaml
.github/workflows/_internal-integration.yaml
.github/workflows/_internal-setup-magento.yaml

Currently, it's really difficult to switch between MageOS mirror and Magento when validating things around release days of MageOS/Magento. This addresses that.
Fixes: N/A
A simple way to switch to the other repo.

ci: easy repo switching
